In [36]:
#%load_ext autoreload
#%autoreload 2
import edited_pipeline as ep
import pipeline as p_l
import pandas as pd
import numpy as np

In [47]:
data = p_l.read_data('/Users/csolisu/Downloads/projects_2012_2013.csv')
data['days_financed'] = pd.to_datetime(data['datefullyfunded']) - pd.to_datetime(data['date_posted'])
data['label'] = data['days_financed'].dt.days.apply(lambda x: 0 if x <= 60 else 1)
d_t = pd.get_dummies(data['teacher_prefix'])
d_t_lst = list(d_t.columns)
d_t['female_teacher'] = d_t['Dr.'] + d_t['Ms.'] + d_t['Mrs.'] 
d_t['male_teacher'] = d_t['Mr.']
p_l.drop_features(d_t, d_t_lst)
data.join(d_t)

final_drop = ['teacher_prefix']
p_l.drop_features(data, final_drop)
tf_dic = {'t': 1, 'f':0}
data = data.replace({'school_charter': tf_dic, 'school_magnet': tf_dic, 'eligible_double_your_impact_match' : tf_dic})


temp_lst = ep.temp_val('2012-01-01','2013-12-31',6,6,60)


In [45]:
clfs, grid = ep.define_clfs_params('small')
models_to_run=['RF','DT','LR']
metric_lst =[ep.roc_auc_sc,ep.precision_at_k,ep.recall_at_k,ep.f1_at_k]
k_lst = [1.0,2.0,5.0,10.0,20.0,30.0,40.0,50.0]

In [48]:
results_df_long = ep.clf_loop(models_to_run,clfs,grid,data,'date_posted','label',temp_lst,metric_lst,k_lst,10)

[]
i am here
[0 1 0 ... 1 0 0]
[[ 0.  1. 23. ...  0.  0.  1.]
 [ 0.  0. 15. ...  0.  0.  0.]
 [ 0.  0. 24. ...  0.  0.  1.]
 ...
 [ 0.  1. 24. ...  0.  0.  1.]
 [ 0.  0. 20. ...  0.  0.  0.]
 [ 0.  0. 11. ...  1.  0.  0.]]
RF
DT


/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value

LR


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework

i am here
[0 1 0 ... 1 0 1]
[[  0.   0.  31. ...   0.   0.   1.]
 [  0.   0. 150. ...   0.   0.   1.]
 [  0.   0.  37. ...   0.   0.   0.]
 ...
 [  0.   0.  25. ...   0.   1.   0.]
 [  0.   0.   7. ...   0.   0.   1.]
 [  0.   0.  24. ...   0.   0.   1.]]
RF
DT


/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value

LR


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework

i am here
[0 1 0 ... 1 1 0]
[[  0.   0.  25. ...   0.   0.   0.]
 [  1.   0.  25. ...   0.   0.   0.]
 [  0.   1. 809. ...   0.   0.   1.]
 ...
 [  0.   0. 738. ...   1.   0.   0.]
 [  0.   0.  20. ...   0.   0.   0.]
 [  0.   1. 156. ...   0.   1.   0.]]
RF
DT


/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value encountered in double_scalars
  F1 = 2 * (precision * recall) / (precision + recall)
/Users/csolisu/30254/Machine_Learning/hw3/edited_pipeline.py:379: RuntimeWarning: invalid value

LR


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/Library/Frameworks/Python.framework

In [50]:
aa = results_df_long.groupby(['train_end_date'])

In [108]:
def rank_classifiers(df,feat,criteria):
    
    aa = df.groupby([feat])
    df[frozenset(dict_key.items())]
    for key, gr in aa:
        add_ord = gr[[criteria]]
        add_ord.drop_duplicates(inplace = True)
        add_ord.sort_values(by =criteria,ascending=False,inplace=True)
        add_ord[key] = np.arange(len(add_ord))
        gr.sort_values(by=criteria, ascending=False,inplace=True)
        total_df = pd.merge(gr,add_ord,on = criteria)
        total_df = total_df[['model_type','clf','parameters',key]]
        df = pd.merge(df,total_df,on = ['model_type','clf','parameters'])
    return df

In [110]:
df_1 = rank_classifiers(df,'train_end_date','p_at_5.0')

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  import sys
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#in

TypeError: unhashable type: 'dict'

In [101]:
add_ord = df[['p_at_5.0']]
#add_ord.sort_values(by ='p_at_5.0',ascending=False,inplace=True)

In [102]:
print(add_ord.shape)
add_ord.drop_duplicates(inplace = True)
add_ord.sort_values(by ='p_at_5.0',ascending=False,inplace=True)
add_ord['ranking'] = np.arange(len(add_ord))

(62, 1)


/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the docume

In [106]:
total_df = pd.merge(df,add_ord,on='p_at_5.0')

In [109]:
df

train_end_date model_type  \
125     2013-05-02         RF   
129     2013-05-02         RF   
127     2013-05-02         RF   
131     2013-05-02         RF   
124     2013-05-02         RF   
182     2013-05-02         LR   
185     2013-05-02         LR   
184     2013-05-02         LR   
183     2013-05-02         LR   
181     2013-05-02         LR   
180     2013-05-02         LR   
135     2013-05-02         RF   
138     2013-05-02         RF   
139     2013-05-02         RF   
134     2013-05-02         RF   
128     2013-05-02         RF   
130     2013-05-02         RF   
179     2013-05-02         LR   
126     2013-05-02         RF   
133     2013-05-02         RF   
137     2013-05-02         RF   
164     2013-05-02         DT   
136     2013-05-02         RF   
165     2013-05-02         DT   
166     2013-05-02         DT   
178     2013-05-02         LR   
132     2013-05-02         RF   
147     2013-05-02         DT   
148     2013-05-02         DT   
176     2013-05-02         LR   
..             ...        ...   
174     2013-05-02         DT   
173     2013-05-02         DT   
175     2013-05-02         DT   
172     2013-05-02         DT   
171     2013-05-02         DT   
170     2013-05-02         DT   
169     2013-05-02         DT   
168     2013-05-02         DT   
167     2013-05-02         DT   
155     2013-05-02         DT   
163     2013-05-02         DT   
152     2013-05-02         DT   
143     2013-05-02         DT   
144     2013-05-02         DT   
145     2013-05-02         DT   
149     2013-05-02         DT   
150     2013-05-02         DT   
162     2013-05-02         DT   
151     2013-05-02         DT   
153     2013-05-02         DT   
154     2013-05-02         DT   
156     2013-05-02         DT   
157     2013-05-02         DT   
161     2013-05-02         DT   
159     2013-05-02         DT   
160     2013-05-02         DT   
142     2013-05-02         DT   
141     2013-05-02         DT   
140     2013-05-02         DT   
158     2013-05-02         DT   

                                                   clf  \
125  (DecisionTreeClassifier(class_weight=None, cri...   
129  (DecisionTreeClassifier(class_weight=None, cri...   
127  (DecisionTreeClassifier(class_weight=None, cri...   
131  (DecisionTreeClassifier(class_weight=None, cri...   
124  (DecisionTreeClassifier(class_weight=None, cri...   
182  LogisticRegression(C=10, class_weight=None, du...   
185  LogisticRegression(C=10, class_weight=None, du...   
184  LogisticRegression(C=10, class_weight=None, du...   
183  LogisticRegression(C=10, class_weight=None, du...   
181  LogisticRegression(C=10, class_weight=None, du...   
180  LogisticRegression(C=10, class_weight=None, du...   
135  (DecisionTreeClassifier(class_weight=None, cri...   
138  (DecisionTreeClassifier(class_weight=None, cri...   
139  (DecisionTreeClassifier(class_weight=None, cri...   
134  (DecisionTreeClassifier(class_weight=None, cri...   
128  (DecisionTreeClassifier(class_weight=None, cri...   
130  (DecisionTreeClassifier(class_weight=None, cri...   
179  LogisticRegression(C=10, class_weight=None, du...   
126  (DecisionTreeClassifier(class_weight=None, cri...   
133  (DecisionTreeClassifier(class_weight=None, cri...   
137  (DecisionTreeClassifier(class_weight=None, cri...   
164  DecisionTreeClassifier(class_weight=None, crit...   
136  (DecisionTreeClassifier(class_weight=None, cri...   
165  DecisionTreeClassifier(class_weight=None, crit...   
166  DecisionTreeClassifier(class_weight=None, crit...   
178  LogisticRegression(C=10, class_weight=None, du...   
132  (DecisionTreeClassifier(class_weight=None, cri...   
147  DecisionTreeClassifier(class_weight=None, crit...   
148  DecisionTreeClassifier(class_weight=None, crit...   
176  LogisticRegression(C=10, class_weight=None, du...   
..                                                 ...   
174  DecisionTreeClassifier(class_weight=None, crit...   
173  DecisionTreeClassifier(class_weight=No

In [113]:
df['new_col'] = df[frozenset(df['parameters'].items())]

TypeError: unhashable type: 'dict'

In [116]:
df['parameters'][125]

{'max_depth': 5,
 'max_features': 'sqrt',
 'min_samples_split': 2,
 'n_estimators': 100,
 'n_jobs': -1}

In [118]:
a = {'max_depth': 5,
 'max_features': 'sqrt',
 'min_samples_split': 2,
 'n_estimators': 100,
 'n_jobs': -1}

b = str(a)

In [119]:
b

"{'max_depth': 5, 'max_features': 'sqrt', 'min_samples_split': 2, 'n_estimators': 100, 'n_jobs': -1}"

In [120]:
import geopandas as gpd
shp_file = '/Users/csolisu/Downloads/tl_2017_us_zcta510/tl_2017_us_zcta510.shp'
geo_zcta = gpd.read_file(shp_file)

In [ ]:
geo_